### ISSUE TITLE
Nothing happens when clicking on log in

### ISSUE THREAD

**Issue by ZuluPilgrim** [CaramelFur/Picsur#60]
I have installed as below. The site comes up but I cannot log in i.e. nothing happens other than a line going across the top, when I click login.
```
version: '3'
services:
  picsur:
    image: ghcr.io/caramelfur/picsur:latest
    container_name: picsur
    ports:
      - '8083:8080' # change the left side of this mapping if 8080 is in use on the host system already
    environment:
      PICSUR_HOST: '0.0.0.0'
      PICSUR_PORT: 8080

      PICSUR_DB_HOST: picsur_postgres
      PICSUR_DB_PORT: 5432
      PICSUR_DB_USERNAME: picsur
      PICSUR_DB_PASSWORD: pwd1  # must match the POSTGRES_PASSWORD in the picsur_postgres: section
      PICSUR_DB_DATABASE: picsur

      PICSUR_ADMIN_PASSWORD: pwd2
      
      PICSUR_MAX_FILE_SIZE: 128000000  # 128 MB
    restart: unless-stopped
    
  picsur_postgres:
    image: postgres:14-alpine
    container_name: picsur_postgres
    environment:
      POSTGRES_DB: picsur
      POSTGRES_PASSWORD: pwd1
      POSTGRES_USER: picsur
    restart: unless-stopped
    volumes:
      - /home/sysadmin/picsur-data:/var/lib/postgresql/data  # this will place all images in the same folder as docker compose
volumes:
  picsur-data:  # if you change the volume mapping, make sure to change this to match
```

The logs are

```
      "id"
    ],
    "message": "Required"
  }
]
[Nest] 45  - 10/05/2023, 10:19:40 PM   ERROR [MainExceptionFilter] (192.168.10.5 -> GET /api/user/me/permissions) InternalFailure: An internal error occurred - Invalid user object, where it should always be valid: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "id"
    ],
    "message": "Required"
  }
]
[Nest] 45  - 10/05/2023, 10:19:40 PM   ERROR [MainExceptionFilter] (192.168.10.5 -> GET /api/info/permissions) InternalFailure: An internal error occurred - Invalid user object, where it should always be valid: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "id"
    ],
    "message": "Required"
  }
]
[Nest] 45  - 10/05/2023, 10:19:57 PM    WARN [ImageManagerModule] Failed to get remove_derivatives_after preference
[Nest] 45  - 10/05/2023, 10:19:57 PM   ERROR [ImageManagerModule] DatabaseFailure: A database error occurred - relation "e_image_backend" does not exist
[Nest] 45  - 10/05/2023, 10:20:20 PM   ERROR [MainExceptionFilter] (192.168.10.5 -> GET /api/info/permissions) InternalFailure: An internal error occurred - Invalid user object, where it should always be valid: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "id"
    ],
    "message": "Required"
  }
]
[Nest] 45  - 10/05/2023, 10:20:57 PM    WARN [ImageManagerModule] Failed to get remove_derivatives_after preference
[Nest] 45  - 10/05/2023, 10:20:57 PM   ERROR [ImageManagerModule] DatabaseFailure: A database error occurred - relation "e_image_backend" does not exist
[Nest] 45  - 10/05/2023, 10:21:33 PM   ERROR [MainExceptionFilter] (192.168.10.5 -> GET /api/info/permissions) InternalFailure: An internal error occurred - Invalid user object, where it should always be valid: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "id"
    ],
    "message": "Required"
  }
]
[Nest] 45  - 10/05/2023, 10:21:33 PM   ERROR [MainExceptionFilter] (192.168.10.5 -> GET /api/user/me/permissions) InternalFailure: An internal error occurred - Invalid user object, where it should always be valid: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "id"
    ],
    "message": "Required"
  }
]
[Nest] 45  - 10/05/2023, 10:21:33 PM   ERROR [MainExceptionFilter] (192.168.10.5 -> GET /api/info) InternalFailure: An internal error occurred - Invalid user object, where it should always be valid: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "id"
    ],
    "message": "Required"
  }
]
[Nest] 45  - 10/05/2023, 10:21:57 PM    WARN [ImageManagerModule] Failed to get remove_derivatives_after preference
[Nest] 45  - 10/05/2023, 10:21:57 PM   ERROR [ImageManagerModule] DatabaseFailure: A database error occurred - relation "e_image_backend" does not exist
[Nest] 45  - 10/05/2023, 10:22:57 PM    WARN [ImageManagerModule] Failed to get remove_derivatives_after preference
[Nest] 45  - 10/05/2023, 10:22:57 PM   ERROR [ImageManagerModule] DatabaseFailure: A database error occurred - relation "e_image_backend" does not exist
[Nest] 45  - 10/05/2023, 10:23:57 PM    WARN [ImageManagerModule] Failed to get remove_derivatives_after preference
[Nest] 45  - 10/05/2023, 10:23:57 PM   ERROR [ImageManagerModule] DatabaseFailure: A database error occurred - relation "e_image_backend" does not exist
[Nest] 45  - 10/05/2023, 10:24:48 PM   ERROR [MainExceptionFilter] (192.168.10.5 -> GET /api/info/permissions) InternalFailure: An internal error occurred - Invalid user object, where it should always be valid: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "id"
    ],
    "message": "Required"
  }
]
[Nest] 45  - 10/05/2023, 10:24:57 PM    WARN [ImageManagerModule] Failed to get remove_derivatives_after preference
[Nest] 45  - 10/05/2023, 10:24:57 PM   ERROR [ImageManagerModule] DatabaseFailure: A database error occurred - relation "e_image_backend" does not exist
[Nest] 45  - 10/05/2023, 10:25:57 PM    WARN [ImageManagerModule] Failed to get remove_derivatives_after preference
[Nest] 45  - 10/05/2023, 10:25:57 PM   ERROR [ImageManagerModule] DatabaseFailure: A database error occurred - relation "e_image_backend" does not exist
[Nest] 45  - 10/05/2023, 10:26:57 PM    WARN [ImageManagerModule] Failed to get remove_derivatives_after preference
[Nest] 45  - 10/05/2023, 10:26:57 PM   ERROR [ImageManagerModule] DatabaseFailure: A database error occurred - relation "e_image_backend" does not exist
[Nest] 45  - 10/05/2023, 10:27:57 PM    WARN [ImageManagerModule] Failed to get remove_derivatives_after preference
[Nest] 45  - 10/05/2023, 10:27:57 PM   ERROR [ImageManagerModule] DatabaseFailure: A database error occurred - relation "e_image_backend" does not exist
```
